
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Nov 11 14:06:40 BRT 2016
//----------------------------------------------------

package calculadora;

/** CUP generated class containing symbol constants. */
public class JMSymbols {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int TIMES = 4;
  public static final int EOF = 0;
  public static final int INT = 6;
}

